services:
  clearml_mmsegmentation:
    build: .
    shm_size: '8gb'
    volumes:
      - "./mmsegmentation:/workspace/mmsegmentation"
    command: /bin/sh -c "while sleep 1000; do :; done"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
